name: "Stoney"
description: "Run Stoney HTTP contracts against a base URL, upload a report, and optionally comment on PRs."
author: "stoneydev"
branding:
  icon: "check-circle"
  color: "purple"

inputs:
  base_url:
    description: "Base URL to run HTTP contracts against (e.g. https://staging.example.com)"
    required: true
  suite:
    description: "Glob or file path for suite files (e.g. contracts/*.yml)"
    required: false
    default: "contracts/*.yml"
  token:
    description: "Optional bearer token used by contracts via ${STONEY_TOKEN}"
    required: false
  timeout_ms:
    description: "Request timeout in ms"
    required: false
    default: "15000"
  retries:
    description: "Retry count for HTTP requests"
    required: false
    default: "2"
  report:
    description: "Report file path"
    required: false
    default: "stoney-report.json"
  upload_artifact:
    description: "Whether to upload the report as an artifact (true/false)"
    required: false
    default: "true"
  artifact_name:
    description: "Artifact name"
    required: false
    default: "stoney-report"
  comment_pr:
    description: "Whether to comment a summary on pull requests (true/false)"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install pnpm
      shell: bash
      run: npm i -g pnpm@10

    - name: Install dependencies
      shell: bash
      run: pnpm install

    - name: Build runner
      shell: bash
      run: pnpm -C packages/runner build

    - name: Run Stoney
      shell: bash
      env:
        STONEY_BASE_URL: ${{ inputs.base_url }}
        STONEY_TOKEN: ${{ inputs.token }}
        STONEY_TIMEOUT_MS: ${{ inputs.timeout_ms }}
        STONEY_RETRIES: ${{ inputs.retries }}
      run: |
        node packages/runner/dist/cli.js run \
          --suite "${{ inputs.suite }}" \
          --report "${{ inputs.report }}"

    - name: Upload report artifact
      if: ${{ inputs.upload_artifact == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: ${{ inputs.report }}

    - name: Comment PR with summary
      if: ${{ inputs.comment_pr == 'true' && github.event_name == 'pull_request' }}
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require("fs");
          const reportPath = "${{ inputs.report }}";
          if (!fs.existsSync(reportPath)) {
            core.warning(`No report found at ${reportPath}, skipping PR comment.`);
            return;
          }

          const report = JSON.parse(fs.readFileSync(reportPath, "utf8"));
          const ok = report.ok === true;
          const emoji = ok ? "✅" : "❌";

          const failed = (report.results || []).filter(r => !r.ok);
          const lines = failed.slice(0, 10).map(r =>
            `- **${r.contract}/${r.id}** → ${r.status ?? "?"} \`${r.method}\` ${r.url}\n  - ${((r.notes||[])[0]) || "Failed"}`
          );

          const body =
            `## ${emoji} Stoney report\n` +
            `**Base URL:** \`${report.baseUrl}\`\n\n` +
            `**Passed:** ${report.passed}/${report.total}\n` +
            `**Failed:** ${report.failed}\n\n` +
            (failed.length ? `### Failures (first ${Math.min(10, failed.length)})\n${lines.join("\n")}\n` : "") +
            `\n_Artifact: \`${{ inputs.artifact_name }}\`_`;

          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body,
          });
